### ISSUE TITLE
Error importing RunningHubInit: No module named 'ComfyUI-Addoor'

### ISSUE THREAD

**Issue by zhuhw19** [Eagle-CN/ComfyUI-Addoor#7]
Error importing RunningHubInit: No module named 'ComfyUI-Addoor'                                                                   
Error importing RunningHubNodeInfo: No module named 'ComfyUI-Addoor'                                                               
Error importing RunningHubWorkflowExecutor: No module named 'ComfyUI-Addoor'                                                       
Error importing RunningHubAccountStatus: No module named 'ComfyUI-Addoor'                                                          
Error importing RunningHubFileSaver: No module named 'ComfyUI-Addoor'                                                              
Error importing RunningHubWorkflowID: No module named 'ComfyUI-Addoor'                                                             
Error importing RunningHubFilePreviewer: No module named 'ComfyUI-Addoor'                                                          
Error importing RunningHubNodeInfoReplace: No module named 'ComfyUI-Addoor'                                                        
Error importing RunningHubImageUploader: No module named 'ComfyUI-Addoor' 
comfyui启动时出现的问题。请问如何解决？ #

**Comment by choui666** [comment]
same problem

**Comment by Crueltyan** [comment]
+1一样的问题

**Comment by fafayqa** [comment]
same problem here too

**Comment by Bobstar88** [comment]
same problem, any solution?

**Comment by Smithvictory25** [comment]
change "comfyUI-Addoor" folder into "ComfyUI_Addoor",everything is ok

**Comment by Romanio1997** [comment]
same problem

**Comment by zhu-que** [comment]
same problem

**Comment by Aljnk** [comment]
Open the file:
`...\ComfyUI\custom_nodes\ComfyUI-Addoor\rp\__init__.py`
Find line
`module = import(f'ComfyUI-Addoor.rp.{module_name}', fromlist=[class_name])`
replace it with
`module = __import__(f'custom_nodes.ComfyUI-Addoor.rp.{module_name}', fromlist=[class_name])`

Not tested, but the problem is gone in console.

**Comment by DemonAlone** [comment]
For the portable version of ComfyUI, navigate to   ComfyUI\custom_nodes\ComfyUI-Addoor and run:  
`pip install -r requirements.txt` . This should resolve the issue. However, it will install `torch‑2.7.1‑cp311‑cp311‑win_amd64.whl`, which is an older build and may break other modules.

**Comment by jxggx** [comment]
same issue

**Comment by bytimer** [comment]
> For the portable version of ComfyUI, navigate to ComfyUI\custom_nodes\ComfyUI-Addoor and run: `pip install -r requirements.txt` . This should resolve the issue. However, it will install `torch‑2.7.1‑cp311‑cp311‑win_amd64.whl`, which is an older build and may break other modules.

I have do "pip install -r requirements.txt",
but still get this error....

**Comment by love530love** [comment]
Error importing RunningHubInit: No module named 'ComfyUI-Addoor'
Error importing RunningHubNodeInfo: No module named 'ComfyUI-Addoor'
Error importing RunningHubWorkflowExecutor: No module named 'ComfyUI-Addoor'
Error importing RunningHubAccountStatus: No module named 'ComfyUI-Addoor'
Error importing RunningHubFileSaver: No module named 'ComfyUI-Addoor'
Error importing RunningHubWorkflowID: No module named 'ComfyUI-Addoor'
Error importing RunningHubFilePreviewer: No module named 'ComfyUI-Addoor'
Error importing RunningHubNodeInfoReplace: No module named 'ComfyUI-Addoor'
Error importing RunningHubImageUploader: No module named 'ComfyUI-Addoor'


The same error is reported. After many attempts, the error cannot be eliminated

**Comment by kowninjae** [comment]
same issue

how about this solution??

...\ComfyUI\custom_nodes\ComfyUI-Addoor\rp\__init__.py

REPLACE 
module = __import__(f'ComfyUI-Addoor.rp.{module_name}', fromlist=[class_name])

Like This
module = __import__(f'custom_nodes.ComfyUI-Addoor.rp.{module_name}', fromlist=[class_name])
